
title = "OKC Robotics Beta 2022 Parameters"
competition = false

[ui]
gamepad1_id = 0
gamepad2_id = 2

[robot]
neo_550_ticks_per_rev = 42
neo_ticks_per_rev = 42
falcon_ticks_per_rev = 2048

[drivetrain]
ticks_per_rev = 42
gear_ratio = 0.103734 # 1 / 9.64
wheel_diameter = 6 # inches

[drivetrain.distance_pid]
Kp = 0.065
Ki = 0.002
Kd = 0.001

[drivetrain.heading_pid]
Kp = 0.07
Ki = 0.0
Kd = 0.00001

[drivetrain.turn_pid]
Kp = 0.05
Ki = 0.0
Kd = 0.009 

[shooter]
normal_shot = 9000 # rpm
against_hub = 8000 # rpm
low_goal = 1500 # rpm
far_shot = 12000 # rpm

[shooter.shoot_pid]
Kp = 0.00001
Ki = 0
Kd = 0.000005
Kf = 0.4

[intake]
gear_ratio = 0.008 # 1 / 125 from 3x 1 / 5 gearboxes in series
raised = 0
extended = 43.75

[intake.deploy_pid]
Kp = 0.07
Ki = 0
Kd = 0.001

[climber]
gear_ratio = 0.0016 # 1 / 625
pulley_diameter = 3 # inches
extend_length = 322281 # 30 * falconTicksPerRev  /  Math.PI * pulleyDiameter;

[climber.tilt_pid]
Kp = 0
Ki = 0
Kd = 0

[climber.extend_pid]
Kp = 0.00001
Ki = 0
Kd = 0.00000001
Kf = 0

[vision]
goal_height = 0 # ft
camera_height = 0 # ft
camera_angle = 0 # deg

[vision.vision_pid]
Kp = 0.03
Ki = 0
Kd = 0.001

[swerve]
# assumes our modules are located in a square, everything should be the same distance from the center
# units are in meters
x_disp = 0.3
y_disp = 0.3